project_id = "pdzbdqyfwcvjpsfgyfdm"

[functions.chat]
verify_jwt = false

[functions.generate-report]
verify_jwt = false

[functions.process-image-ocr]
verify_jwt = false

[functions.transcribe-audio]
verify_jwt = false
